from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(366, 638)
        MainWindow.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(36)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.outputlabel = QtWidgets.QLabel(self.centralwidget)
        self.outputlabel.setGeometry(QtCore.QRect(10, 10, 341, 91))
        self.outputlabel.setFrameShape(QtWidgets.QFrame.Box)
        self.outputlabel.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.outputlabel.setObjectName("outputlabel")
        self.sevenbutton = QtWidgets.QPushButton(self.centralwidget,clicked=lambda: self.press_it("7"))
        self.sevenbutton.setGeometry(QtCore.QRect(10, 110, 75, 75))
        self.sevenbutton.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(False)
        font.setWeight(50)
        self.sevenbutton.setFont(font)
        self.sevenbutton.setObjectName("sevenbutton")
        self.eightbutton = QtWidgets.QPushButton(self.centralwidget,clicked=lambda: self.press_it("8"))
        self.eightbutton.setGeometry(QtCore.QRect(100, 110, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.eightbutton.setFont(font)
        self.eightbutton.setObjectName("eightbutton")
        self.ninebutton = QtWidgets.QPushButton(self.centralwidget,clicked=lambda: self.press_it("9"))
        self.ninebutton.setGeometry(QtCore.QRect(190, 110, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.ninebutton.setFont(font)
        self.ninebutton.setObjectName("ninebutton")
        self.plusbutton = QtWidgets.QPushButton(self.centralwidget,clicked=lambda: self.press_it("+"))
        self.plusbutton.setGeometry(QtCore.QRect(280, 110, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.plusbutton.setFont(font)
        self.plusbutton.setObjectName("plusbutton")
        self.fourbutton = QtWidgets.QPushButton(self.centralwidget,clicked=lambda: self.press_it("4"))
        self.fourbutton.setGeometry(QtCore.QRect(10, 200, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.fourbutton.setFont(font)
        self.fourbutton.setObjectName("fourbutton")
        self.fivebutton = QtWidgets.QPushButton(self.centralwidget,clicked=lambda: self.press_it("5"))
        self.fivebutton.setGeometry(QtCore.QRect(100, 200, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.fivebutton.setFont(font)
        self.fivebutton.setObjectName("fivebutton")
        self.sixbutton = QtWidgets.QPushButton(self.centralwidget,clicked=lambda: self.press_it("6"))
        self.sixbutton.setGeometry(QtCore.QRect(190, 200, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.sixbutton.setFont(font)
        self.sixbutton.setObjectName("sixbutton")
        self.dividebutton = QtWidgets.QPushButton(self.centralwidget,clicked=lambda: self.press_it("/"))
        self.dividebutton.setGeometry(QtCore.QRect(280, 200, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.dividebutton.setFont(font)
        self.dividebutton.setObjectName("dividebutton")
        self.onebutton = QtWidgets.QPushButton(self.centralwidget,clicked=lambda: self.press_it("1"))
        self.onebutton.setGeometry(QtCore.QRect(10, 290, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.onebutton.setFont(font)
        self.onebutton.setObjectName("onebutton")
        self.twobutton = QtWidgets.QPushButton(self.centralwidget,clicked=lambda: self.press_it("2"))
        self.twobutton.setGeometry(QtCore.QRect(100, 290, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.twobutton.setFont(font)
        self.twobutton.setObjectName("twobutton")
        self.threebutton = QtWidgets.QPushButton(self.centralwidget,clicked=lambda: self.press_it("3"))
        self.threebutton.setGeometry(QtCore.QRect(190, 290, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.threebutton.setFont(font)
        self.threebutton.setObjectName("threebutton")
        self.multiplybutton = QtWidgets.QPushButton(self.centralwidget,clicked=lambda: self.press_it("*"))
        self.multiplybutton.setGeometry(QtCore.QRect(280, 290, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.multiplybutton.setFont(font)
        self.multiplybutton.setObjectName("multiplybutton")
        self.zerobutton = QtWidgets.QPushButton(self.centralwidget,clicked=lambda: self.press_it("0"))
        self.zerobutton.setGeometry(QtCore.QRect(50, 380, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.zerobutton.setFont(font)
        self.zerobutton.setObjectName("zerobutton")
        self.equalbutton = QtWidgets.QPushButton(self.centralwidget,clicked=lambda: self.math_it())
        self.equalbutton.setGeometry(QtCore.QRect(150, 380, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.equalbutton.setFont(font)
        self.equalbutton.setObjectName("equalbutton")
        self.minusbutton = QtWidgets.QPushButton(self.centralwidget,clicked=lambda: self.press_it("-"))
        self.minusbutton.setGeometry(QtCore.QRect(250, 380, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.minusbutton.setFont(font)
        self.minusbutton.setObjectName("minusbutton")
        self.cbutton = QtWidgets.QPushButton(self.centralwidget,clicked=lambda: self.press_it("C"))
        self.cbutton.setGeometry(QtCore.QRect(220, 470, 100, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.cbutton.setFont(font)
        self.cbutton.setObjectName("cbutton")
        self.cancelbutton = QtWidgets.QPushButton(self.centralwidget,clicked=lambda: self.remove_it())
        self.cancelbutton.setGeometry(QtCore.QRect(70, 470, 100, 80))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.cancelbutton.setFont(font)
        self.cancelbutton.setObjectName("cancelbutton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
    #Display the result function.
    def math_it(self):
        screen=self.outputlabel.text()
        answer=eval(screen)
        #Display result.
        self.outputlabel.setText(str(answer))   
    #Remove a character.
    def remove_it(self):
        #Grab whats on the screen already.
        screen=self.outputlabel.text()
        #Remove the last character.
        screen=screen[:-1]  
        #Display whats on the screen.
        self.outputlabel.setText(screen) 
    def press_it(self,pressed):
        if pressed=="C":
            self.outputlabel.setText("0")
        else:
            if self.outputlabel.text()=="0":
                 self.outputlabel.setText("")         
            self.outputlabel.setText(f"{self.outputlabel.text()}{pressed}")    
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Calculator"))
        self.outputlabel.setText(_translate("MainWindow", "0"))
        self.sevenbutton.setText(_translate("MainWindow", "7"))
        self.eightbutton.setText(_translate("MainWindow", "8"))
        self.ninebutton.setText(_translate("MainWindow", "9"))
        self.plusbutton.setText(_translate("MainWindow", "+"))
        self.fourbutton.setText(_translate("MainWindow", "4"))
        self.fivebutton.setText(_translate("MainWindow", "5"))
        self.sixbutton.setText(_translate("MainWindow", "6"))
        self.dividebutton.setText(_translate("MainWindow", "/"))
        self.onebutton.setText(_translate("MainWindow", "1"))
        self.twobutton.setText(_translate("MainWindow", "2"))
        self.threebutton.setText(_translate("MainWindow", "3"))
        self.multiplybutton.setText(_translate("MainWindow", "x"))
        self.zerobutton.setText(_translate("MainWindow", "0"))
        self.equalbutton.setText(_translate("MainWindow", "="))
        self.minusbutton.setText(_translate("MainWindow", "-"))
        self.cbutton.setText(_translate("MainWindow", "C"))
        self.cancelbutton.setText(_translate("MainWindow", "<<"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
